const teamlist = [
  {
    team: "Alaskan Thunder",
    wins: 0,
    losses: 0,
    overtime: 0,
    points: 0,
    goalsFor: 0,
    goalsAllowed: 0,
    forward: "Erik Galuska",
    defense: "Andrew Levy",
    goalie: "Ricky Novia",
  },
  {
    team: "American Revolution",
    wins: 0,
    losses: 0,
    overtime: 0,
    points: 0,
    goalsFor: 0,
    goalsAllowed: 0,
    forward: "Mikey Papa",
    defense: "Owen Brown",
    goalie: "Mike Marotta",
  },
  {
    team: "Boondock Beluga Whales",
    wins: 0,
    losses: 0,
    overtime: 0,
    points: 0,
    goalsFor: 0,
    goalsAllowed: 0,
    forward: "Austin Ingarra",
    defense: "Darren Barille",
    goalie: "Alec Fowler",
  },
  {
    team: "Florida Tropics",
    wins: 0,
    losses: 0,
    overtime: 0,
    points: 0,
    goalsFor: 0,
    goalsAllowed: 0,
    forward: "Aidan Murray",
    defense: "Chris Horowitz",
    goalie: "Collin Salatto",
  },
  {
    team: "Smashville Chippewas",
    wins: 0,
    losses: 0,
    overtime: 0,
    points: 0,
    goalsFor: 0,
    goalsAllowed: 0,
    forward: "Sal DeLucia",
    defense: "Vinny Cleary",
    goalie: "Tom Bishop",
  },
  {
    team: "Southside Spartans",
    wins: 0,
    losses: 0,
    overtime: 0,
    points: 0,
    goalsFor: 0,
    goalsAllowed: 0,
    forward: "Chris Papa",
    defense: "Erik Levenduski",
    goalie: "Matt Palma",
  },
];

module.exports = teamlist;
